name: Autograding Tests
on: [push, pull_request]

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run GitHub Classroom Tests
        uses: education/autograding@v1
